---
- hosts: localhost
  connection: local
  vars:
    ansible_python_interpreter: /Users/celeguim/Python-Envs/Ansible-Docker/bin/python3

  tasks:
    - name: Ensure Docker image is built from Dockerfile
      docker_image:
        name: celeguim/jvminfo
        tag: v1
        source: build
        build:
          path: .
          pull: yes
        state: present
        push: yes

    - name: Ensure jvminfo container is running
      docker_container:
        image: celeguim/jvminfo:v1
        name: jvminfo
        state: started
        exposed_ports: "8081"
        published_ports: "18080:8081"
