apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: restrict-image-registries
spec:
  validationFailureAction: Audit
  background: true
  rules:
    - name: restrict-image-registries
      match:
        any:
          - resources:
              kinds:
                - Pod
      validate:
        message: "Images must come from an approved registry."
        foreach:
          - list: "request.object.spec.containers"
            deny:
              conditions:
                all:
                  - key: "{{ element.image }}"
                    operator: NotEquals
                    value: "registry.example.com/*"
                  - key: "{{ element.image }}"
                    operator: NotEquals
                    value: "*.dkr.ecr.*.amazonaws.com/*"
