apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: require-pdb

spec:
  validationFailureAction: Audit
  background: false

  rules:
    - name: require-pdb
      match:
        any:
          - resources:
              kinds:
                - Deployment
                - StatefulSet
              operations:
                - CREATE
                - UPDATE

      context:
        - name: pdb_count
          apiCall:
            urlPath: >-
              /apis/policy/v1/namespaces/{{request.namespace}}/poddisruptionbudgets
            jmesPath: >-
              items[?label_match(
                spec.selector.matchLabels,
                `{{ request.object.spec.template.metadata.labels }}`
              )] | length(@)

      validate:
        message: >-
          Workload must have a matching PodDisruptionBudget.

        deny:
          conditions:
            any:
              - key: "{{ pdb_count }}"
                operator: LessThan
                value: 1
