apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: require-service-account
  annotations:
    policies.kyverno.io/title: Require Service Account
    policies.kyverno.io/category: Best Practices
    policies.kyverno.io/severity: medium
    policies.kyverno.io/subject: Pod,ServiceAccount

spec:
  validationFailureAction: Audit
  background: true

  rules:
    - name: require-explicit-service-account
      match:
        any:
          - resources:
              kinds:
                - Pod

      validate:
        message: >-
          Pods must define an explicit ServiceAccount
          and must not use the default ServiceAccount.

        deny:
          conditions:
            any:
              - key: "{{ request.object.spec.serviceAccountName || '' }}"
                operator: Equals
                value: ""

              - key: "{{ request.object.spec.serviceAccountName || 'default' }}"
                operator: Equals
                value: default
