# Application Name
spring.application.name=jvminfo

# Web Context Path
server.servlet.context-path=/

# Spring Endpoints exposure enabled
management.endpoints.web.exposure.include=health,info,metrics,mappings

# Actuator port
management.server.port=9090

# Enable health endpoint details
management.endpoint.health.show-details=always

# Enable endpoints for liveness and rediness
management.endpoint.health.probes.enabled=true

# Enable liveness and readiness
management.health.livenessstate.enabled=true
management.health.readinessstate.enabled=true

# Enable the app custom readiness and liveness
# The name must be different from the reserved "liveness" and "readiness"
# Otherwise it will be a collision
management.health.group.readiness.include=customReadinessIndicator
management.health.group.liveness.include=customLivenessIndicator
