apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namePrefix: dev4-
namespace: dev4
labels:
  - pairs:
      environment: dev4
patches:
  - path: patches/deploy-patch.yaml
  - path: patches/hpa-patch.yaml
resources:
  - ../../base
