defaults:
  targetRevision: main
  autosync: true

applications:
  # - name: java-app1
  #   namespace: celeghin
  #   project: default
  #   repoURL: https://github.com/celeguim/DevOps.git
  #   targetRevision: main
  #   path: Java/app1/kustomize/overlays/dev/result
  #   cluster: in-cluster
  #   autosync: true

  # - name: java-app2
  #   namespace: celeghin
  #   project: default
  #   repoURL: https://github.com/celeguim/DevOps.git
  #   targetRevision: main
  #   path: Java/app2/kustomize/overlays/dev/result
  #   cluster: in-cluster
  #   autosync: true

  - name: jvminfo-v9
    namespace: celeghin
    project: default
    repoURL: https://github.com/celeguim/jvminfo.git
    targetRevision: v9
    path: kubernetes/kustomize/overlays/dev1/result
    cluster: in-cluster
    autosync: true

  - name: jvminfo-v10
    namespace: celeghin
    project: default
    repoURL: https://github.com/celeguim/jvminfo.git
    targetRevision: v10
    path: kubernetes/kustomize/overlays/dev2/result
    cluster: in-cluster
    autosync: true
