defaults:
  targetRevision: main
  autosync: true

applications:
  - name: dev1
    namespace: celeghin
    project: default
    repoURL: https://github.com/celeguim/jvminfo.git
    targetRevision: jvminfo-v10
    path: kubernetes/kustomize/overlays/dev1/result
    cluster: in-cluster
    autosync: true

  - name: dev2
    namespace: celeghin
    project: default
    repoURL: https://github.com/celeguim/jvminfo.git
    targetRevision: jvminfo-v10
    path: kubernetes/kustomize/overlays/dev2/result
    cluster: in-cluster
    autosync: true
