apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namePrefix: dev3-
namespace: dev3
labels:
  - pairs:
      environment: dev3
patches:
  - path: patches/deploy-patch.yaml
  - path: patches/hpa-patch.yaml
resources:
  - ../../base
