apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: jvminfo-keda
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: jvminfo-v10-deployment
  minReplicaCount: 1
  maxReplicaCount: 3
  triggers:
    - type: prometheus
      metadata:
        serverAddress: http://prometheus-server.monitoring.svc.cluster.local
        metricName: http_requests_total
        # calcula a média de requisições por segundo no último minuto [1m]
        query: sum(rate(http_server_requests_seconds_count{uri="/"}[1m]))
#        threshold: '5' # escala se passar de 5 requests/seg
        threshold: '0.5' # escala se passar de 30 requests/min (30/60=0.5)
