apiVersion: v1
kind: Service
metadata:
  name: jvminfo-v9-svc-lb
spec:
  type: LoadBalancer
  # O Docker Desktop mapeia isso automaticamente para o localhost
  # mas no minikube eh necessario
  # minikube tunnel
  ports:
    - port: 8080
      targetPort: 8080
      name: app-port
    - port: 9090
      targetPort: 9090
      name: metrics-port
  selector:
    app: jvminfo-v9
