name: Hello World

on:
  workflow_dispatch:

jobs:
  hello:
    runs-on: ubuntu-latest

    steps:
      - name: Hello
        run: |
          echo "Hello World"
          echo "Repository: ${{ github.repository }}"
          echo "Branch: ${{ github.ref_name }}"
