apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
# namePrefix: dev-
namespace: dev1
labels:
  - pairs:
      environment: dev1
patches:
  - path: patches/deploy-patch.yaml
resources:
  - ../../base
